version: 1.0.{build}

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: off

test_script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test --no-fail-fast --verbose --all -- --nocapture
